services:

    php-apache-node:
        container_name: gallery-service
        build:
            context: ./docker
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html
        ports:
            - 9090:80
            - 5173:5173
            - 5174:5174
        depends_on:
            - mysql
        networks:
            - gallery

    mysql:
        image: mariadb:lts-jammy
        ports:
            - 33006:3306

        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - gallery


volumes:
    db-data: ~
networks:
    gallery:
        driver: bridge
