services:

  laravel-gallery:
        build:
            context: ./docker
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.2/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-8080}:8080'
            # - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - gallery
        depends_on:
            - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gallery
    ports:
        - 3396:3306
    networks:
        - gallery
    volumes:
            - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
        - 9001:80
    environment:
        - PMA_ARBITRARY=1
    networks:
        - gallery
    depends_on:
        - mysql

  nodejs:
    image: node:20-bullseye-slim
    ports:
        - 5173:5173
    working_dir: /app
    volumes:
        - ./:/app
    networks:
        - gallery
    depends_on:
        - laravel-gallery
        - mysql
    entrypoint: sh -c "npm install && npm run dev"

networks:
    gallery:
        driver: bridge
volumes:
    db-data: ~
